alias faggy='say -v Good\ News faggy faggy faggy faggy faggy faggy faggy faggy'
alias galias='alias | grep'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
alias reload="source ~/.zshrc"
alias pyserver="python -m SimpleHTTPServer"
alias rbserver="ruby -run -e httpd ."
alias ssh-key-copy="cat ~/.ssh/id_rsa.pub | pbcopy"
alias ssh-list='cat ~/.ssh/config'
alias traling-spaces="sed -i '' 's/[[:space:]]\{1,\}$//'"
